routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', 'HomeController@index')->name('home');
Auth::routes();
//---------------------Client-------------------------
Route::name('clients.list')->get('/clients/list','ClientController@getIndex');
Route::get('/clients/search','ClientController@search');
Route::get('/clients/search/dni','ClientController@searchDNI');
Route::get('/clients/get/{dni}','ClientController@getClient');
Route::resource('clients','ClientController',['except' => ['edit']]); 

//----------------Dealers-----------------------------
Route::name('dealers.list')->get('/dealers/list','DealerController@getIndex');
Route::get('/dealers/search','DealerController@search');
Route::get('/dealers/combo','DealerController@combo');
Route::get('/dealers/get/{id}','DealerController@getDealer');
Route::resource('dealers','DealerController',['except' => ['edit', 'show']]); 

//---------------------Laboratory---------------------------------
Route::name('laboratories.list')->get('/laboratories/list','LaboratoryController@getIndex');
Route::get('/laboratories/search','LaboratoryController@search');
Route::get('/laboratories/combo','LaboratoryController@combo');
Route::get('/laboratories/get/{id}','LaboratoryController@getLaboratory');
Route::resource('laboratories','LaboratoryController',['except' => ['edit', 'show']]); 

//--------------------Presentation---------------------------------
Route::name('presentations.list')->get('/presentations/list','PresentationController@getIndex');
Route::get('/presentations/combo','PresentationController@combo');
Route::get('/presentations/search','PresentationController@search');
Route::get('/presentations/get/{id}','PresentationController@getPresentation');
Route::resource('presentations','PresentationController',['except' => ['edit', 'show']]);

//-------------------------Medicine------------------------------------
Route::name('medicines.list')->get('/medicines/list','MedicineController@getIndex');
Route::get('/medicines/search','MedicineController@search');
Route::get('/medicines/combo','MedicineController@combo');
Route::get('/medicines/get/{id}','MedicineController@getMedicine');
Route::get('/medicines/saleprice/{id}','MedicineController@getMedicinePrice');
Route::resource('medicines','MedicineController',['except' => ['edit', 'show']]); 

//-------------------------Purchase------------------------------------
Route::name('purchases.list')->get('/purchases/list','PurchaseController@getIndex');
Route::name('purchases.report')->get('/purchases/report','PurchaseController@getReport');
Route::get('/purchases/search','PurchaseController@search');
Route::get('/purchases/search_report','PurchaseController@report');
Route::get('/purchases/code','PurchaseController@code');
Route::get('/purchases/show/{id}','PurchaseController@showDetails');

Route::name('purchases.create')->get('/purchases/create','PurchaseController@create');
Route::post('/purchases','PurchaseController@store');
Route::get('/purchases','PurchaseController@index');

//--------------------PurchaseDetail---------------------------------
Route::post('/purchasedetails','PurchaseDetailController@store');
Route::put('/purchasedetails/stock','PurchaseDetailController@updateStock');

//-------------------------- Sale ------------------------------------
Route::name('sales.list')->get('/sales/list','SaleController@getIndex');
Route::name('sales.report')->get('/sales/report','SaleController@getReport');
Route::get('/sales/search_report','SaleController@report');

Route::name('sales.bill')->get('/sales/bill','SaleController@bill');
Route::name('sales.invoce')->get('/sales/invoce','SaleController@invoce');
Route::name('sales.cancel')->get('/sales/cancel','SaleController@getCancel');

Route::get('/sales/search','SaleController@search');
Route::get('/sales/code/invoce','SaleController@numberInvoce');
Route::get('/sales/code/bill','SaleController@numberBill');
Route::get('/sales/show/{series}/{number}','SaleController@showDetails');
Route::put('/sales/edit/{series}/{number}','SaleController@cancelSale');

Route::post('/sales','SaleController@store');
Route::get('/sales','SaleController@index');
Route::get('/sales/{series}/{number}','SaleController@show');
//--------------------------SaleDetail---------------------------------
Route::post('/saledetails','SaleDetailController@store');
Route::put('/saledetails/stock','SaleDetailController@updateStock');
//----------------------- USER  -------
Route::get('/getuser','UserAuthController@getUserAuth');
Route::get('/getuser/{id}','UserAuthController@getSaleUser');
Route::get('/roles','RoleController@index');

resources/views/layouts/_errors.blade.php
@if(count($errors) > 0)
<div class="alert alert-danger">
	<ul>
		@foreach($errors->all() as $error)
		<li>{{ $error }}</li>
		@endforeach
	</ul>
</div>
@endif

resources/views/layouts/_messages.blade.php
@if(session()->has('message'))
<div class="alert alert-success">
	{{ session()->get('message') }}
</div>
@endif

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>       
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>
                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/base.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Meta, title, CSS, favicons, etc. -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta name="csrf-token" content="{{ csrf_token() }}">

  <title>{{ config('app.name', 'Laravel') }}</title>
  <!-- Bootstrap -->
  <link href="../vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
  <!-- Font Awesome -->
  <link href="../vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
  <!-- NProgress -->
  <link href="../vendors/nprogress/nprogress.css" rel="stylesheet">
  <!-- iCheck -->
  <link href="../vendors/iCheck/skins/flat/green.css" rel="stylesheet">

  <!-- bootstrap-progressbar -->
  <link href="../vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
  <!-- JQVMap -->
  <link href="../vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet"/>
  <!-- bootstrap-daterangepicker -->
  <link href="../vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">

  <!-- Custom Theme Style -->
  <link href="../build/css/custom.min.css" rel="stylesheet">
</head>

<body class="nav-md">
  <div class="container body">
    <div class="main_container">
      <div class="col-md-3 left_col">
        <div class="left_col scroll-view">
          <div class="navbar nav_title" style="border: 0;">
            <a href="{{ url('/') }}" class="site_title"><i class="fa fa-plus"></i> {{ config('app.name', 'Laravel') }}</a>
          </div>

          <div class="clearfix"></div>
          <br />

          <!-- sidebar menu -->
          <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
              <h3>Mantenimientos</h3>
              <ul class="nav side-menu">
                <li><a><i class="fa fa-user"></i> Usuarios <span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu">
                    <li><a href="{{ route('register') }}">Nuevo Usuario</a></li>
                  </ul>
                </li>
                <li><a><i class="fa fa-users"></i> Clientes <span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu">
                    <li><a href={{ route('clients.list') }}>Lista</a></li>
                    <li><a href={{ route('clients.create') }}>Nuevo</a></li>
                  </ul>
                </li>
                <li><a><i class="fa fa-ambulance"></i> Distribuidores <span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu">
                    <li><a href={{ route('dealers.list') }}>Lista</a></li>
                    <li><a href={{ route('dealers.create') }}>Nuevo</a></li>
                  </ul>
                </li>
                <li><a><i class="fa fa-flask"></i> Laboratorios<span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu">
                    <li><a href={{ route('laboratories.list') }}>Lista</a></li>
                    <li><a href={{ route('laboratories.create') }}>Nuevo</a></li>
                  </ul>
                </li>
                <li><a><i class="fa fa-medkit"></i> Medicamentos <span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu">
                    <li><a href={{ route('medicines.list') }}>Lista</a></li>
                    <li><a href={{ route('medicines.create') }}>Nuevo</a></li>
                  </ul>
                </li>
              </ul>
            </div>
            <div class="menu_section">
              <h3>PROCESOS</h3>
              <ul class="nav side-menu">
                <li><a><i class="fa fa-shopping-cart"></i> Compras <span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu">
                    <li><a href={{ route('purchases.list') }}>Lista de Compras</a></li>
                    <li><a href={{ route('purchases.create') }}>Realizar Compra</a></li>
                    <li><a href={{ route('purchases.report')}}>Reporte de Compras</a></li>
                  </ul>
                </li>
                <li><a><i class="fa fa-money"></i> Ventas <span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu">
                      <li><a href={{ route('sales.list') }}>Lista de Ventas</a></li>
                      <li><a> Realizar de Ventas  <span class="fa fa-chevron-down"></a> 
                          <ul class="nav child_menu">
                            <li><a href={{ route('sales.bill') }}>Boleta</a></li>
                            <li><a href={{ route('sales.invoce') }}>Factura</a></li>
                          </ul>
                      </li>
                      <li><a href={{ route('sales.report')}}>Reporte Venta</a></li>
                      <li><a href={{ route('sales.cancel') }}>Anular Venta</a></li>

                  </ul>
                </li>
              </ul>
            </div>

          </div>
          <!-- /sidebar menu -->

          <!-- /menu footer buttons -->
          <div class="sidebar-footer hidden-small ">
              <a class="pull-right" href="{{ route('logout') }}"
                  onclick="event.preventDefault();
                  document.getElementById('logout-form').submit();">
                  <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
              </a>
              <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
              </form>
          </div>
          <!-- /menu footer buttons -->
        </div>
      </div>

      <!-- top navigation -->
      <div class="top_nav">
        <div class="nav_menu">
          <nav>
            <div class="nav toggle">
              <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
              <!-- Authentication Links -->
              @if (Auth::guest())
                  <li><a href="{{ route('login') }}">Login</a></li>
                  <li><a href="{{ route('register') }}">Register</a></li>
              @else
                  <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                          {{ Auth::user()->name }} <span class="fa fa-angle-down"></span>
                      </a>

                      <ul class="dropdown-menu" role="menu">
                          <li>
                              <a href="{{ route('logout') }}"
                                  onclick="event.preventDefault();
                                           document.getElementById('logout-form').submit();">
                                  Logout
                              </a>

                              <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                  {{ csrf_field() }}
                              </form>
                          </li>
                      </ul>
                  </li>
              @endif
          </ul>
          </nav>
        </div>
      </div>
      <!-- /top navigation -->

      <!-- page content -->
      <div id="app">
        <div class="right_col" role="main">
          @yield('content')
        </div>
      </div>
      <!-- /page content -->
      
      <!-- footer content -->
      <footer>
        <div class="pull-right">
          <a href="https://ilinktic.com">iLink - TIC</a>
        </div>
        <div class="clearfix"></div>
      </footer>
       <!-- /footer content -->
    </div>
  </div>
  
  <script src="{{asset('js/app.js')}}"></script>
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet">
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.26/vue.min.js"></script>
  <!-- jQuery -->
  <script src="../vendors/jquery/dist/jquery.min.js"></script>
  <!-- Bootstrap -->
  <script src="../vendors/bootstrap/dist/js/bootstrap.min.js"></script>
  <!-- FastClick -->
  <script src="../vendors/fastclick/lib/fastclick.js"></script>
  <!-- NProgress -->
  <script src="../vendors/nprogress/nprogress.js"></script>
  <!-- Chart.js -->
  <script src="../vendors/Chart.js/dist/Chart.min.js"></script>
  <!-- gauge.js -->
  <script src="../vendors/gauge.js/dist/gauge.min.js"></script>
  <!-- bootstrap-progressbar -->
  <script src="../vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
  <!-- iCheck -->
  <script src="../vendors/iCheck/icheck.min.js"></script>
  <!-- Skycons -->
  <script src="../vendors/skycons/skycons.js"></script>
  <!-- Flot -->
  <script src="../vendors/Flot/jquery.flot.js"></script>
  <script src="../vendors/Flot/jquery.flot.pie.js"></script>
  <script src="../vendors/Flot/jquery.flot.time.js"></script>
  <script src="../vendors/Flot/jquery.flot.stack.js"></script>
  <script src="../vendors/Flot/jquery.flot.resize.js"></script>
  <!-- Flot plugins -->
  <script src="../vendors/flot.orderbars/js/jquery.flot.orderBars.js"></script>
  <script src="../vendors/flot-spline/js/jquery.flot.spline.min.js"></script>
  <script src="../vendors/flot.curvedlines/curvedLines.js"></script>
  <!-- DateJS -->
  <script src="../vendors/DateJS/build/date.js"></script>
  <!-- JQVMap -->
  <script src="../vendors/jqvmap/dist/jquery.vmap.js"></script>
  <script src="../vendors/jqvmap/dist/maps/jquery.vmap.world.js"></script>
  <script src="../vendors/jqvmap/examples/js/jquery.vmap.sampledata.js"></script>
  <!-- bootstrap-daterangepicker -->
  <script src="../vendors/moment/min/moment.min.js"></script>
  <script src="../vendors/bootstrap-daterangepicker/daterangepicker.js"></script>
  <!-- Custom Theme Scripts -->
  <script src="../build/js/custom.min.js"></script>
  <!-- jQuery Smart Wizard -->
    <script src="../vendors/jQuery-Smart-Wizard/js/jquery.smartWizard.js"></script>


</body>
</html>